### PR TITLE
Logger can be overridden from external sources

### PR DESCRIPTION
**Pull request by Ruxton**
Adds a log interface so the log can be integrated with external sources  (Like negroni's logger or a logstash logger)

```golang
  logger := negroni.NewLogger()
  n := negroni.New(negroni.NewRecovery(), logger, negroni.NewStatic(http.Dir("public")))
  n.Use(restgate.New("X-Auth-Key", "X-Auth-Secret", restgate.Static, restgate.Config{Key: []string{"test"}, Secret: []string{"abcdefg"}, Logger:logger}))
```

### CODE REVIEW

**Comment by pjebs** [comment]
Can you simplify `ALogger` to only include `Printf`?

**Comment by Ruxton** [comment]
I built it to line up with the std log package, which is capable of all the above, but I guess cutting it down to whatever you use is the smart thing to do.

**Comment by Ruxton** [comment]
@pjebs have cleaned it up now

**Comment by pjebs** [comment]
For backwards compatibility one more change to  L68:
```go
var std = New(os.Stderr, "", LstdFlags)
```

This was from the standard library source code: https://golang.org/src/log/log.go#L73

Then I will merge.

Thank you for your contribution.

**Comment by Ruxton** [comment]
@pjebs should all be resolved now

**Comment by pjebs** [comment]
Awesome work. Fixed up `log`.`LstdFlags` afterwards.

**Pull request merged**
